name = "topchina-proxy-subscription"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV 存储配置（用于缓存）
[[kv_namespaces]]
binding = "TOPCHINA_CACHE"
id = "313eeb72c26a4db3a25b7f2481b62297"
preview_id = "313eeb72c26a4db3a25b7f2481b62297"

# 环境变量（可选）
[vars]
CACHE_DURATION = "3600"
MAX_NODES_LIMIT = "200"

# 路由配置
[triggers]
crons = ["0 */1 * * *"]  # 每小时触发一次，用于预热缓存

# 自定义域名（可选）
# [[routes]]
# pattern = "topchina.yourdomain.com/*"
# zone_name = "yourdomain.com"
